// CONSTANTEN
const CANVAS_BREEDTE = 800;
const CANVAS_HOOGTE = 600;
const ACHTERGROND_BREEDTE = 1000;
const GROND_Y = 540;

const NANONAUT_Y_VERSNELLING = 1;
const NANONAUT_X_SNELHEID = 2;
const NANONAUT_SPRONG_SNELHEID = 20;
const NANONAUT_BREEDTE = 181;
const NANONAUT_HOOGTE = 229;
const NANONAUT_NR_ANIMATIEFRAMES = 7;
const NANONAUT_ANIMATIE_SNELHEID = 3;
const NANONAUT_MAX_GEZONDHEID = 100;
const NANONAUT_MAX_MANA = 100;
const NANONAUT_SLIDEN_MANA = 50;
const NANONAUT_MANA_PER_TICK = 0.05;
const NANONAUT_SLIDEN_SNELHEID = 30;

const SPATIEBALK_CODE = 32;
const LINKS_PIJL_CODE = 37;
const BOVEN_PIJL_CODE = 38;
const RECHTS_PIJL_CODE = 39;
const BENEDEN_PIJL_CODE = 40;
const PAUSE_CODE = 112;

const ROBOT_NR_ANIMATIEFRAMES = 9;
const ROBOT_ANIMATIE_SNELHEID = 5;
const ROBOT_BREEDTE = 141;
const ROBOT_HOOGTE = 139;
const ROBOT_X_SNELHEID = 4;
const MIN_AFSTAND_TUSSEN_ROBOTS = 400;
const MAX_AFSTAND_TUSSEN_ROBOTS = 1200;
const MAX_ACTIEVE_ROBOTS = 3;

const SCHERMSCHUD_RADIUS = 16;

const SPEEL_MODUS = 0;
const GAME_OVER_SPELMODUS = 1;
const PAUZE_SPELMODUS = 2;